import type { MetadataRoute } from "next";
import { sitemapPaths } from "@/lib/seo/sitemap";

/**
 * URLs only — deliberately no `lastModified`, `changeFrequency`, or `priority`.
 *
 * This file is prerendered at build time, so the only `lastModified` we could
 * honestly produce is the build timestamp — identical for all 32 URLs, and
 * regenerated by every deploy. That tells Google "all 32 pages changed at once"
 * on a CSS tweak, which is never true. Google discounts `lastmod` once it detects
 * it is unreliable, so a uniform build-time value buys nothing and costs
 * credibility. Omitting it is the honest signal.
 *
 * `changeFrequency` and `priority` are ignored by Google outright, so they were
 * removed with it rather than left as decorative noise.
 *
 * If per-page `lastmod` is wanted later, it has to come from real per-route
 * modification data — e.g. the last commit touching each route's source and its
 * backing data file. That was considered and rejected for now: it needs `git`
 * present in the build container, and a shallow clone (a common CI default)
 * silently returns one identical date for every file, reintroducing exactly the
 * problem this change removes — but harder to notice.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return sitemapPaths().map((url) => ({ url }));
}
