import type { Metadata } from "next";
import Link from "next/link";
import { Eyebrow } from "@/components/ui/eyebrow";
import { cn } from "@/lib/utils";
import { GetTermsDocument } from "./getterms-document";

/**
 * Branded shell shared by the Privacy, Terms, and Cookies pages. The document
 * body itself is dynamically generated by GetTerms — see GetTermsDocument.
 */

const GETTERMS = {
  account: "7RS3i",
  lang: "en-us",
  env: "https://gettermscdn.com",
} as const;

export type LegalKey = "privacy" | "terms" | "cookies";

type LegalDoc = {
  path: string;
  tab: string;
  title: string;
  intro: string;
  /** GetTerms `data-getterms-document` slug. */
  slug: string;
  description: string;
};

export const LEGAL_DOCS: Record<LegalKey, LegalDoc> = {
  privacy: {
    path: "/privacy",
    tab: "Privacy Policy",
    title: "Privacy Policy",
    intro:
      "How Impeccabyte collects, uses, and protects your information when you use our website and payment services.",
    slug: "privacy",
    description:
      "How Impeccabyte collects, uses, and protects your information when you use our website and merchant services.",
  },
  terms: {
    path: "/terms",
    tab: "Terms of Service",
    title: "Terms of Service",
    intro: "The terms that govern your use of the Impeccabyte website and merchant services.",
    slug: "terms-of-service",
    description:
      "The terms that govern your use of the Impeccabyte website and merchant services.",
  },
  cookies: {
    path: "/cookies",
    tab: "Cookie Policy",
    title: "Cookie Policy",
    intro:
      "How Impeccabyte uses cookies and similar technologies on our website — and the choices you have.",
    slug: "cookies",
    description:
      "How Impeccabyte uses cookies and similar technologies on our website, and the choices you have.",
  },
};

const TAB_ORDER: LegalKey[] = ["privacy", "terms", "cookies"];

export function legalMetadata(key: LegalKey): Metadata {
  const doc = LEGAL_DOCS[key];
  return {
    title: doc.title,
    description: doc.description,
    alternates: { canonical: doc.path },
    openGraph: { title: doc.title, description: doc.description, url: doc.path },
  };
}

export function LegalPage({ active }: { active: LegalKey }) {
  const doc = LEGAL_DOCS[active];

  return (
    <>
      {/* Hero */}
      <section
        className="border-b border-border-subtle"
        style={{
          background:
            "radial-gradient(90% 120% at 50% -30%, var(--amber-50), var(--paper) 60%)",
        }}
      >
        <div className="mx-auto max-w-[920px] px-6 pb-10 pt-16 text-center">
          <Eyebrow>Legal</Eyebrow>
          <h1
            className="mt-3.5 font-display font-semibold text-ink-900"
            style={{ fontSize: "clamp(34px,4.6vw,52px)", letterSpacing: "-0.025em", lineHeight: 1.05 }}
          >
            {doc.title}
          </h1>
          <p className="mx-auto mt-4 max-w-[560px] text-[17px] leading-relaxed text-ink-600">
            {doc.intro}
          </p>

          {/* Document switcher */}
          <nav
            aria-label="Legal documents"
            className="mt-[26px] inline-flex flex-wrap justify-center gap-1.5 rounded-pill border border-border-default bg-white p-[5px] shadow-sm"
          >
            {TAB_ORDER.map((key) => {
              const tab = LEGAL_DOCS[key];
              const on = key === active;
              return (
                <Link
                  key={key}
                  href={tab.path}
                  aria-current={on ? "page" : undefined}
                  className={cn(
                    "rounded-pill px-[18px] py-2 text-[14px] font-semibold transition-colors",
                    on
                      ? "bg-clay-500 text-[#FBF6EE]"
                      : "text-ink-600 hover:text-clay-600",
                  )}
                >
                  {tab.tab}
                </Link>
              );
            })}
          </nav>
        </div>
      </section>

      <GetTermsDocument
        account={GETTERMS.account}
        slug={doc.slug}
        lang={GETTERMS.lang}
        env={GETTERMS.env}
        shortName={doc.title}
      />
    </>
  );
}
